create route for editing, creating post
codepitaka/pitaka-web pull request #22
Opened 2020-02-01 10:38 UTC by chullino

2020-02-03 11:15 UTC, chullino commented
### 헤로쿠 환경변수 설정
- pitaka-web-review 앱의 `APPMODE`: `RVW`
- pitaka-web-dev 앱의 `APPMODE`: `DEV`
- pitaka-web 앱의 `APPMODE`: `PRD`

해당 환경변수를 받아서, 어느 서버(DEV SERVER, PRD SERVER, LOCAL SERVER)에 연결할 것인지 선택.

2020-02-03 12:10 UTC, chullino commented
main 함수 형식 변경
`engine = 리턴하는 메소드(engine)` 형식에서 `engine.이벤트 메소드()` 형식으로 전부 변경.

2020-02-04 13:58 UTC, davin111 requested changes
궁금한 것과 수정하거나 추가하면 좋겠는 부분을 달아보았습니다. 덧붙여, 특히 프론트엔드쪽 PR은 관련된 주요 화면의 스크린샷이 있어도 좋을 것 같습니다! 그리고 conflict가 해소되어야 해요.

직접 deploy된 환경 들어가서 구경해봤는데, 신기하네요! 멋집니다. 그런데 DB 관련해서 문제가 있는지, 지금은 자동 저장이 안되네요.

2020-02-04 13:58 UTC, davin111 commented on src/engine/engine.go
> +	engineWrapper.engine.Static("/css", path)
오 딱 이런 거 원하고 있었습니다, 지난 회고록(https://github.com/codepitaka/pitaka-server/wiki/Davin-회고록#20200202-회고)에서 언급했듯!

2020-02-04 13:58 UTC, davin111 commented on src/static/templates/edit/edit.html
> +		<script type="text/javascript">
요거 어느 정도 각 url의 view에 따른 test들 파일별로 추가해주면 좋지 않을까요? javascript로 짜여진 로직들이 있으니까요!

2020-02-04 13:58 UTC, davin111 commented on src/static/templates/create/create.html
> +		<script>
어느 정도 각 url의 view에 따른 test 파일들이 있어야할 것 같아요. javascript로 짜여진 꽤 복잡한 로직들이 있으니까요!

2020-02-04 13:58 UTC, davin111 commented on src/static/templates/create/create.html
> +					<input type="button" class="BOLD" value="Bold" onclick="document.execCommand('bold')" />
html 각 요소들 class를 대문자로 적는 것이 convention인가요? 약간 생소한 거 같기도 해서 질문드립니다. 덧붙여, class는 여러 파일에 걸쳐 영향을 주기도 하는데, case-sensitive한지도 궁금하네요.

2020-02-04 13:58 UTC, davin111 commented on src/static/templates/create/create.html
> +				<input id="publish" type="button" value="publish 하기" onclick="publish()" />
publish() 함수 실행에서 내용이 없을 때 alert를 띄우기보다, 버튼 자체를 내용이 없을 때 disabled 시키면 어떨까요?

2020-02-04 13:58 UTC, davin111 commented on src/static/templates/create/create.html
> +				const terminalPart = urlParts.pop() || urlParts.pop()  // handle potential trailing slash
trailing slash 따로 처리 안 하면 문제가 생기던가요?

2020-02-04 13:58 UTC, davin111 commented on src/static/templates/create/create.html
> +				window.location.href="https://pitaka-jnclz.run.goorm.io"
요것은 general한 것으로 바꾸어야할 것 같습니다? 어떤 위치가 의도되는 것인가요?

2020-02-04 13:58 UTC, davin111 commented on src/static/templates/create/create.html
> +						.then(postId => '/post='+postId+'/'+'edit')
이렇게 url이 이동할 때, refresh 되면서 끊김이 발생하지 않나요? 실제로 어떻게 보여지고 빠르게 쓰기 시작할 때 문제가 없는지 궁금합니다. url이 바뀌어도 아래의 코드들을 보면 create.html의 화면에 계속 남아있는 것이 가정되는 것 같아서 특히 궁금합니다. 그리고 만약 자동 저장 되어서 url이 바뀐 상태에서, 새로고침을 하면 어떻게 되나요?

2020-02-04 13:58 UTC, davin111 commented on src/static/templates/edit/edit.html
> +				var url = 'https://port-3000-pitaka.run.goorm.io/posts';
이것도 url이 general하게 수정되어야할 것 같아요. 도메인 단위까지 필요 없이 코드 써서 이용 가능할 거 같아요.

2020-02-06 07:01 UTC, chullino commented on src/static/templates/create/create.html
> +					<input type="button" class="BOLD" value="Bold" onclick="document.execCommand('bold')" />
아 convention 아닐거고, 제가 관리를 못한 상황인 듯 싶어요! class는 case-sensitive한 상황이 맞을거에요. [스택오버플로 링크](https://stackoverflow.com/questions/12533926/are-class-names-in-css-selectors-case-sensitive) 달아둡니다.

2020-02-06 07:02 UTC, chullino commented on src/static/templates/create/create.html
> +				<input id="publish" type="button" value="publish 하기" onclick="publish()" />
더 좋은 방안이네요! 변경해둘게요!

2020-02-06 07:03 UTC, chullino commented on src/static/templates/create/create.html
> +				const terminalPart = urlParts.pop() || urlParts.pop()  // handle potential trailing slash
문제는 안생기는데, 일종의 관습인 듯? 싶어요. 혹시나에 대비한?

2020-02-06 07:03 UTC, chullino commented on src/static/templates/create/create.html
> +				window.location.href="https://pitaka-jnclz.run.goorm.io"
맞아요. 바꿔둘게요!

2020-02-06 07:07 UTC, chullino commented on src/static/templates/create/create.html
> +						.then(postId => '/post='+postId+'/'+'edit')
url이동할 때, history객체를 replace하는 식이라서 끊김은 발생하지 않아요. 만약 location.repace였으면 끊김이 생기고 변경되었을 것이구요. 
추가로 말씀하신 새로고침에는 대비하지는 못했는데, 대비해둬야겠어요!

2020-02-06 07:07 UTC, chullino commented on src/static/templates/edit/edit.html
> +				var url = 'https://port-3000-pitaka.run.goorm.io/posts';
맞아요! 변경해둘게요!

2020-02-06 07:18 UTC, chullino commented on src/static/templates/edit/edit.html
> +		<script type="text/javascript">
맞아요. 제안하고 싶은 게 있는데, 저희 벡티로 옮긴 후에 테스트 추가해도 괜찮을까요? 아니면, 중복될 듯 싶어서요!

2020-02-06 07:19 UTC, chullino commented on src/static/templates/edit/edit.html
> +		<script type="text/javascript">
만약 test코드가 없어서 코드 가독성이 너무 낮은 듯 싶으면 추가해둘게요! 어짜피 한번은 뇌를 짜야하니 생각해보니 큰 비용은 아닐 듯 싶어요. 두번 하면 좀 더 탄탄해질 것같기도 하구요.

2020-02-07 11:55 UTC, chullino commented on src/static/templates/edit/edit.html
> +				var url = 'https://port-3000-pitaka.run.goorm.io/posts';
done

2020-02-07 11:55 UTC, chullino commented on src/static/templates/create/create.html
> +				window.location.href="https://pitaka-jnclz.run.goorm.io"
done

2020-02-08 04:35 UTC, davin111 commented on src/static/templates/create/create.html
> +				window.location.href="https://pitaka-jnclz.run.goorm.io"
네, 그게 좋은 것 같습니다! 쓴 글을 확인할 수 있는 페이지!

2020-02-08 04:36 UTC, davin111 commented on src/static/templates/edit/edit.html
> +		<script type="text/javascript">
@chullino Vecty 로 언제 옮기게 될까요? 그게 더 효율적일 거 같으시면 그래도 괜찮습니다. 물론 그때 테스트를 잘 짜면서 사후적으로 고칠 것도 잘 체크하구요! 저도 PR할 예정인데 테스트에 대해서 그럼 약간 고민스럽게 되어서, 옮기려면 빨리 옮기면 좋겠다 싶어요!

2020-02-08 11:16 UTC, chullino commented on src/static/templates/create/create.html
> +						.then(postId => '/post='+postId+'/'+'edit')
다음 PR에서 처리할예정.

2020-02-08 15:01 UTC, chullino commented
view 라우트, 테스트코드 제거했어요.

2020-02-09 04:36 UTC, davin111 approved these changes

2020-02-09 04:36 UTC, merged

2020-02-09 04:58 UTC, davin111 commented on src/static/templates/edit/edit.html
> +		<script type="text/javascript">
@chullino 요거는 merge된 이후지만 시간 날 때 답 주세요!

2020-02-09 05:00 UTC, chullino commented on src/static/templates/edit/edit.html
> +		<script type="text/javascript">
벡티로는 이번주에 옮겨도 좋아요!

2020-02-09 05:00 UTC, chullino commented on src/static/templates/edit/edit.html
> +		<script type="text/javascript">
사실 결정은 된 사항이지만, 지난주 풀리퀘까지는 일단 올리기로 했으니, 올리고 새로 개발하는 내용서부터 차차 VECTY로 옮기면 될 듯 싶어요.